<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-JV1I1EE" failures="1" tests="2" name="tests.Direct_Payment_to_Visa_Test" time="120.775" errors="0" timestamp="2023-12-12T09:10:05 IST" skipped="1">
  <testcase classname="tests.Direct_Payment_to_Visa_Test" name="testVisaPayment" time="77.125">
    <skipped/>
  </testcase> <!-- testVisaPayment -->
  <system-out/>
  <testcase classname="tests.Direct_Payment_to_Visa_Test" name="testVisaPayment" time="43.650">
    <failure message="The following asserts failed:
	Assert failed- Reading data without selecting Account expected [http://dbankdemo.com/bank/external/xfer-visa] but found [http://dbankdemo.com/bank/external/xfer-visa-process],
	Assert failed - Accepting 0 amount expected [http://dbankdemo.com/bank/external/xfer-visa] but found [http://dbankdemo.com/bank/external/xfer-visa-process],
	Assert failed - Accepting 0.001 Amount expected [http://dbankdemo.com/bank/external/xfer-visa] but found [http://dbankdemo.com/bank/external/xfer-visa-process],
	Service Unavailable,
	Assert failed- Reading data without selecting Account expected [http://dbankdemo.com/bank/external/xfer-visa] but found [http://dbankdemo.com/bank/external/xfer-visa-process],
	Assert failed - Accepting 0 amount expected [http://dbankdemo.com/bank/external/xfer-visa] but found [http://dbankdemo.com/bank/external/xfer-visa-process],
	Assert failed - Accepting 0.001 Amount expected [http://dbankdemo.com/bank/external/xfer-visa] but found [http://dbankdemo.com/bank/external/xfer-visa-process],
	Service Unavailable" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Assert failed- Reading data without selecting Account expected [http://dbankdemo.com/bank/external/xfer-visa] but found [http://dbankdemo.com/bank/external/xfer-visa-process],
Assert failed - Accepting 0 amount expected [http://dbankdemo.com/bank/external/xfer-visa] but found [http://dbankdemo.com/bank/external/xfer-visa-process],
Assert failed - Accepting 0.001 Amount expected [http://dbankdemo.com/bank/external/xfer-visa] but found [http://dbankdemo.com/bank/external/xfer-visa-process],
Service Unavailable,
Assert failed- Reading data without selecting Account expected [http://dbankdemo.com/bank/external/xfer-visa] but found [http://dbankdemo.com/bank/external/xfer-visa-process],
Assert failed - Accepting 0 amount expected [http://dbankdemo.com/bank/external/xfer-visa] but found [http://dbankdemo.com/bank/external/xfer-visa-process],
Assert failed - Accepting 0.001 Amount expected [http://dbankdemo.com/bank/external/xfer-visa] but found [http://dbankdemo.com/bank/external/xfer-visa-process],
Service Unavailable
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at tests.Direct_Payment_to_Visa_Test.testVisaPayment(Direct_Payment_to_Visa_Test.java:62)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- testVisaPayment -->
  <system-out/>
</testsuite> <!-- tests.Direct_Payment_to_Visa_Test -->
